require("spec.runner")()
local P = require("__stdlib2__/area").Position ---@diagnostic disable-line: unused-local

describe("MapPositionClass", function()

  describe("Class	table: 0x561df64abdb0:", function() end)
  describe("__add:", function() end)
  describe("__call:", function() end)
  describe("__class	MapPosition:", function() end)
  describe("__concat:", function() end)
  describe("__div:", function() end)
  describe("__eq:", function() end)
  describe("__index:", function() end)
  describe("__mod:", function() end)
  describe("__mul:", function() end)
  describe("__newindex:", function() end)
  describe("__sub:", function() end)
  describe("__tostring:", function() end)
  describe("__unm:", function() end)
  describe("to_area:", function() end)
  describe("to_area_left_top:", function() end)
  describe("to_chunk_area:", function() end)
  describe("to_chunk_position:", function() end)
  describe("to_chunk_tile_area:", function() end)
  describe("to_pixel_position:", function() end)
  describe("to_tile_position:", function() end)
end)
